services:
  beetle:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
        - VITE_BASE_API_URL=https://bloomapidev.delightfulgrass-0b885410.westus.azurecontainerapps.io
        - VITE_ADMIN_ACCESS_KEY=beetlerocks
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s